engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "evostream/**.py"
exclude_paths:
- "evostream/tests.py"
