language: python

python:
  - 2.7

env:
  - DJANGO=1.4.22
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.11
  - DJANGO=1.8.11
  - DJANGO=1.9.4

matrix:
  include:
    - python: 3.5
      env: DJANGO=1.9.4

install:
  - pip install coveralls
  - pip install -q Django==$DJANGO
  - pip install --upgrade mock

script:
  - coverage run ./manage.py test

after_success:
  - coveralls